// Description: This file contains REST API requests for managing contacts.
// It includes requests to get all contacts and a single contact by ID.

//LOCALHOST:3000
### Get all contacts
GET http://localhost:3000/contacts

### Get single contact
GET http://localhost:3000/contacts/68285946d998a0d172d74f6f

### Create contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Eunice",
  "lastName": "Daniels",
  "email": "eunice@example.com",
  "favoriteColor": "blue",
  "birthday": "1990-07-05"
}

### Update contact
PUT http://localhost:3000/contacts/68285946d998a0d172d74f6f
Content-Type: application/json

{
  "firstName": "Isaac",
  "lastName": "Stuart",
  "email": "isaac@example.com",
  "favoriteColor": "Red",
  "birthday": "1990-01-01"
}

### Delete contact
DELETE http://localhost:3000/contacts/68263237ecfd6afe834f315e



////////////////////////////////////////////////////////////


//PRODUCTION: RENDER
### Get all contacts
GET https://cse341-contacts-api-frsq.onrender.com/contacts

### Get single contact
GET https://cse341-contacts-api-frsq.onrender.com/contacts/681cc919fc672da58d0f32c7

### Create contact
POST https://cse341-contacts-api-frsq.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Moffat",
  "lastName": "Smith",
  "email": "moffat@example.com",
  "favoriteColor": "purple",
  "birthday": "1995-05-15"
}

### Update contact
PUT https://cse341-contacts-api-frsq.onrender.com/contacts/681cc919fc672da58d0f32c7
Content-Type: application/json

{
  "firstName": "Isaac",
  "lastName": "Stuart",
  "email": "isaac@example.com",
  "favoriteColor": "Red",
  "birthday": "1990-01-01"
}

### Delete contact
DELETE https://cse341-contacts-api-frsq.onrender.com/contacts/68285027112b2f05e3d84d5b